---
title: Charlotte Trash Schedule
author: Eric Morgan
email: ericreedmorgan@gmail.com
description: Calendars for CLT trash and recycle schedule
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
