---
title: Charlotte Trash Schedule
author: Eric Morgan
email: ericreedmorgan@gmail.com
description: "\U0001F4C6 2021 Garbage and Recycling schedule for Charlotte, NC available
  as Google Calendar or iCal."
baseurl: "/ubuild-jekyll"
url: https://www.charlottetrashschedule.com
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
